const SAMPLE_FLASHCARDS = [
  {
    id: 1,
    category: "React",
    subcategory: "React Basics",
    question: "What is React?",
    answer: "A library for managing user interfaces",
    options: [
      "A library for managing user interfaces",
      "A JavaScript framework for backend development",
      "A CSS pre-processor",
      "A database query language",
    ],
  },
  {
    id: 2,
    category: "CCNA",
    subcategory: "OSI Model",
    question: "What does OSI stand for?",
    answer: "Open Systems Interconnection",
    options: [
      "Open Systems Interconnection",
      "Operating System Interface",
      "Optimal Signal Indicator",
      "Organized System Integration",
    ],
  },
  {
    id: 3,
    category: "CCNA",
    subcategory: "OSI Model",
    question: "Which layer of the OSI model deals with routing?",
    answer: "Network Layer",
    options: [
      "Data Link Layer",
      "Network Layer",
      "Transport Layer",
      "Application Layer",
    ],
  },
  {
    id: 4,
    category: "CCNA",
    subcategory: "IP Addressing",
    question: "What is the default subnet mask for a Class C IP address?",
    answer: "255.255.255.0",
    options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"],
  },
  {
    id: 5,
    category: "CCNA",
    subcategory: "Networking Protocols",
    question: "Which protocol is used for sending email?",
    answer: "SMTP",
    options: ["HTTP", "FTP", "SMTP", "SNMP"],
  },
  {
    id: 6,
    category: "CCNA",
    subcategory: "Networking Concepts",
    question: "What is the purpose of a VLAN?",
    answer: "To segment a network",
    options: [
      "To create a virtual environment",
      "To encrypt data packets",
      "To segment a network",
      "To prioritize network traffic",
    ],
  },
  {
    id: 7,
    category: "React",
    subcategory: "React Basics",
    question: "What is JSX?",
    answer: "JavaScript XML",
    options: [
      "JavaScript Extension",
      "JavaScript XML",
      "JavaScript X-Path",
      "JavaScript JSON",
    ],
  },
  {
    id: 8,
    category: "React",
    subcategory: "React Hooks",
    question: "Which hook is used for side-effects?",
    answer: "useEffect",
    options: ["useState", "useEffect", "useContext", "useReducer"],
  },
  {
    id: 9,
    category: "React",
    subcategory: "State Management",
    question: "What is Redux?",
    answer: "A state management library",
    options: [
      "A JavaScript framework",
      "A state management library",
      "A CSS framework",
      "A backend library",
    ],
  },
  {
    id: 10,
    category: "React",
    subcategory: "Routing",
    question: "What is React Router?",
    answer: "A routing library for React",
    options: [
      "A state management library",
      "A routing library for React",
      "A CSS framework",
      "A backend library",
    ],
  },
  {
    id: 11,
    category: "React",
    subcategory: "React Basics",
    question: "What is a React component?",
    answer: "A reusable piece of UI",
    options: [
      "A function",
      "A reusable piece of UI",
      "An HTML element",
      "A JavaScript object",
    ],
  },
  {
    id: 12,
    category: "React",
    subcategory: "React Basics",
    question: "What is React's virtual DOM?",
    answer: "An in-memory representation of the real DOM elements",
    options: [
      "A physical DOM",
      "An in-memory representation of the real DOM elements",
      "A set of APIs",
      "A database",
    ],
  },
  {
    id: 13,
    category: "React",
    subcategory: "React Basics",
    question: "What is a React Fragment?",
    answer: "A way to return multiple elements",
    options: [
      "A way to return multiple elements",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 14,
    category: "React",
    subcategory: "React Basics",
    question: "What is a React Portal?",
    answer:
      "A way to render children into a DOM node that exists outside the DOM hierarchy",
    options: [
      "A way to render children into a DOM node that exists outside the DOM hierarchy",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 15,
    category: "React",
    subcategory: "React Basics",
    question: "What is Context in React?",
    answer:
      "A way to pass data through the component tree without having to pass props down manually",
    options: [
      "A way to pass data through the component tree without having to pass props down manually",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 16,
    category: "React",
    subcategory: "React Basics",
    question: "What is a React Hook?",
    answer:
      "A function that lets you use state and other React features without writing a class",
    options: [
      "A function that lets you use state and other React features without writing a class",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 17,
    category: "CCNA",
    subcategory: "IP Addressing",
    question: "What is the range of private IP addresses for Class A?",
    answer: "10.0.0.0 to 10.255.255.255",
    options: [
      "10.0.0.0 to 10.255.255.255",
      "172.16.0.0 to 172.31.255.255",
      "192.168.0.0 to 192.168.255.255",
      "None of the above",
    ],
  },
  {
    id: 18,
    category: "CCNA",
    subcategory: "Networking Protocols",
    question: "What is NAT? (Network Address Translation)",
    answer: "Network Address Translation",
    options: [
      "Network Address Translation",
      "Network Allocation Table",
      "Network Access Token",
      "None of the above",
    ],
  },
  {
    id: 19,
    category: "CCNA",
    subcategory: "Networking Concepts",
    question: "What is a firewall used for?",
    answer: "To control incoming and outgoing network traffic",
    options: [
      "To filter spam emails",
      "To control incoming and outgoing network traffic",
      "To improve Wi-Fi signal strength",
      "To encrypt data",
    ],
  },
  {
    id: 20,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is Python?",
    answer: "A high-level programming language",
    options: [
      "A type of snake",
      "A high-level programming language",
      "A data storage format",
      "A computer manufacturer",
    ],
  },
  {
    id: 21,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is the main use of Python?",
    answer: "Web development, data analysis, artificial intelligence, and more",
    options: [
      "Web development",
      "Data analysis",
      "Artificial intelligence",
      "All of the above",
    ],
  },
  {
    id: 22,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is the PEP 8 style guide for Python?",
    answer: "A set of conventions for writing Python code",
    options: [
      "A type of snake",
      "A computer manufacturer",
      "A set of conventions for writing Python code",
      "A Python package",
    ],
  },
  {
    id: 23,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is the purpose of indentation in Python?",
    answer: "To indicate blocks of code",
    options: [
      "To make the code look pretty",
      "To indicate blocks of code",
      "To create comments",
      "To import libraries",
    ],
  },
  {
    id: 24,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is a Python variable?",
    answer: "A symbolic name for a value",
    options: [
      "A data structure",
      "A symbolic name for a value",
      "A Python module",
      "A reserved keyword",
    ],
  },
  {
    id: 25,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is a Python function?",
    answer: "A reusable block of code",
    options: [
      "A type of variable",
      "A Python module",
      "A reusable block of code",
      "A reserved keyword",
    ],
  },
  {
    id: 26,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is a Python list?",
    answer: "An ordered collection of items",
    options: [
      "An ordered collection of items",
      "A Python module",
      "A reserved keyword",
      "A type of loop",
    ],
  },
  {
    id: 27,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is a Python dictionary?",
    answer: "A collection of key-value pairs",
    options: [
      "A collection of key-value pairs",
      "A Python module",
      "A reserved keyword",
      "A type of loop",
    ],
  },
  {
    id: 28,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is a Python class?",
    answer: "A blueprint for creating objects",
    options: [
      "A blueprint for creating objects",
      "A Python module",
      "A reserved keyword",
      "A type of loop",
    ],
  },
  {
    id: 29,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is a Python module?",
    answer: "A file containing Python code",
    options: [
      "A blueprint for creating objects",
      "A file containing Python code",
      "A reserved keyword",
      "A type of loop",
    ],
  },
  {
    id: 30,
    category: "Python",
    subcategory: "Python Basics",
    question: "What is a Python package?",
    answer: "A collection of Python modules",
    options: [
      "A file containing Python code",
      "A collection of Python modules",
      "A reserved keyword",
      "A type of loop",
    ],
  },
  {
    id: 31,
    category: "Django",
    subcategory: "Django Basics",
    question: "What is Django?",
    answer: "A high-level Python web framework",
    options: [
      "A type of snake",
      "A high-level Python web framework",
      "A data storage format",
      "A computer manufacturer",
    ],
  },
  {
    id: 32,
    category: "Django",
    subcategory: "Django Basics",
    question: "What is the main use of Django?",
    answer: "Building web applications",
    options: [
      "Building web applications",
      "Data analysis",
      "Artificial intelligence",
      "All of the above",
    ],
  },
  {
    id: 33,
    category: "Django",
    subcategory: "Django Basics",
    question: "What is the Django ORM?",
    answer: "Object-Relational Mapping",
    options: [
      "Object-Relational Mapping",
      "Object-Relational Database",
      "Object-Relational Model",
      "None of the above",
    ],
  },
  {
    id: 34,
    category: "Django",
    subcategory: "Django Basics",
    question: "What is a Django model?",
    answer: "A Python class that represents a database table",
    options: [
      "A Python function",
      "A Python class that represents a database table",
      "A Python module",
      "A reserved keyword",
    ],
  },
  {
    id: 35,
    category: "Django",
    subcategory: "Django Basics",
    question: "What is a Django view?",
    answer:
      "A Python function that takes a web request and returns a web response",
    options: [
      "A Python class",
      "A Python function that takes a web request and returns a web response",
      "A Python module",
      "A reserved keyword",
    ],
  },
  {
    id: 36,
    category: "Django",
    subcategory: "Django Basics",
    question: "What is a Django template?",
    answer: "A text file containing HTML and template tags",
    options: [
      "A Python function",
      "A text file containing HTML and template tags",
      "A Python module",
      "A reserved keyword",
    ],
  },
  {
    id: 37,
    category: "Django",
    subcategory: "Django Basics",
    question: "What is a Django URL pattern?",
    answer: "A regular expression that maps to a view function",
    options: [
      "A Python class",
      "A regular expression that maps to a view function",
      "A Python module",
      "A reserved keyword",
    ],
  },

  {
    id: 38,
    category: "CCNA",
    subcategory: "Network Protocols",
    question: "What is the main difference between TCP and UDP?",
    answer: "TCP is connection-oriented, UDP is connectionless",
    options: [
      "TCP is faster than UDP",
      "TCP is connection-oriented, UDP is connectionless",
      "TCP uses IP, UDP uses ICMP",
      "None of the above",
    ],
  },
  {
    id: 39,
    category: "CCNA",
    subcategory: "Network Protocols",
    question: "What port does UDP use for DNS queries?",
    answer: "53",
    options: ["53", "80", "443", "8080"],
  },
  {
    id: 40,
    category: "CCNA",
    subcategory: "Switching",
    question: "Which STP state immediately follows the blocking state?",
    answer: "Listening",
    options: ["Listening", "Learning", "Forwarding", "Disabled"],
  },
  {
    id: 41,
    category: "CCNA",
    subcategory: "Wireless Networking",
    question: "What wireless standard operates at 5GHz frequency?",
    answer: "802.11a",
    options: ["802.11a", "802.11b", "802.11g", "802.11n"],
  },
  {
    id: 42,
    category: "CCNA",
    subcategory: "Wireless Security",
    question: "What is the purpose of WPA in a wireless network?",
    answer: "To provide security through encryption",
    options: [
      "To provide security through encryption",
      "To boost signal strength",
      "To provide routing services",
      "None of the above",
    ],
  },
  {
    id: 43,
    category: "CCNA",
    subcategory: "Switching",
    question: "What is the default STP priority?",
    answer: "32768",
    options: ["1024", "4096", "32768", "65536"],
  },
  {
    id: 44,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the maximum hop count for OSPF?",
    answer: "Infinite",
    options: ["15", "16", "Infinite", "None of the above"],
  },
  {
    id: 45,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the 'show ip ospf neighbor' command?",
    answer: "To display OSPF neighbor information",
    options: [
      "To display OSPF routes",
      "To display OSPF neighbor information",
      "To display OSPF settings",
      "None of the above",
    ],
  },
  {
    id: 46,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the OSPF Router ID format?",
    answer: "32-bit number",
    options: [
      "16-bit number",
      "32-bit number",
      "48-bit number",
      "64-bit number",
    ],
  },
  {
    id: 47,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the default hello interval for OSPF?",
    answer: "10 seconds",
    options: ["5 seconds", "10 seconds", "30 seconds", "60 seconds"],
  },
  {
    id: 48,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the OSPF DR (Designated Router)?",
    answer: "To optimize OSPF network traffic",
    options: [
      "To optimize OSPF network traffic",
      "To act as a backup router",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 49,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the 'cost' in OSPF?",
    answer: "To determine the best path for data packets",
    options: [
      "To determine the best path for data packets",
      "To set the priority of a router",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 50,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the OSPF LSA (Link-State Advertisement)?",
    answer: "To advertise routing information",
    options: [
      "To advertise routing information",
      "To encrypt OSPF packets",
      "To set the priority of a router",
      "None of the above",
    ],
  },
  {
    id: 51,
    category: "CCNA",
    subcategory: "OSPF",
    question:
      "What is the default OSPF hello interval on a point-to-point network?",
    answer: "10 seconds",
    options: ["5 seconds", "10 seconds", "30 seconds", "60 seconds"],
  },
  {
    id: 52,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the OSPF network command used for?",
    answer: "To specify which interfaces will participate in OSPF",
    options: [
      "To specify which interfaces will participate in OSPF",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 53,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the OSPF 'area range' command?",
    answer: "To summarize routes at an area boundary",
    options: [
      "To summarize routes at an area boundary",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 54,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the 'show ip ospf interface' command?",
    answer: "To display OSPF-related interface information",
    options: [
      "To display OSPF routes",
      "To display OSPF-related interface information",
      "To display OSPF settings",
      "None of the above",
    ],
  },
  {
    id: 55,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the OSPF RID (Router ID) used for?",
    answer: "To uniquely identify a router in an OSPF network",
    options: [
      "To uniquely identify a router in an OSPF network",
      "To set OSPF priority",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 56,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the OSPF 'network' command?",
    answer: "To enable OSPF on specified interfaces",
    options: [
      "To enable OSPF on specified interfaces",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 57,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the OSPF 'passive-interface' command?",
    answer: "To prevent OSPF updates from being sent out an interface",
    options: [
      "To prevent OSPF updates from being sent out an interface",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 58,
    category: "CCNA",
    subcategory: "OSPF",
    question:
      "What is the purpose of the OSPF 'default-information originate' command?",
    answer: "To generate a default route into OSPF",
    options: [
      "To generate a default route into OSPF",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 59,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the OSPF 'area' command?",
    answer: "To assign an interface to a specific OSPF area",
    options: [
      "To assign an interface to a specific OSPF area",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 60,
    category: "CCNA",
    subcategory: "OSPF",
    question: "What is the purpose of the OSPF 'router-id' command?",
    answer: "To manually set the OSPF router ID",
    options: [
      "To manually set the OSPF router ID",
      "To set OSPF priority",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 61,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question: "What is the purpose of the OSPF 'redistribute' command?",
    answer: "To inject routes from another routing protocol into OSPF",
    options: [
      "To inject routes from another routing protocol into OSPF",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 62,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question: "What is the purpose of the OSPF 'summary-address' command?",
    answer: "To manually configure OSPF route summarization",
    options: [
      "To manually configure OSPF route summarization",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 63,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question: "What is the purpose of the OSPF 'timers' command?",
    answer: "To manually set OSPF hello and dead intervals",
    options: [
      "To manually set OSPF hello and dead intervals",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 73,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question: "What is the purpose of the OSPF 'virtual-link' command?",
    answer: "To configure an OSPF virtual link",
    options: [
      "To configure an OSPF virtual link",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 74,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question:
      "What is the purpose of the OSPF 'clear ip ospf process' command?",
    answer: "To reset the OSPF process",
    options: [
      "To reset the OSPF process",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 75,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question:
      "What is the purpose of the OSPF 'show ip ospf database' command?",
    answer: "To display the OSPF link-state database",
    options: [
      "To display the OSPF link-state database",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 76,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question: "What is the purpose of the OSPF 'show ip ospf route' command?",
    answer: "To display the OSPF routing table",
    options: [
      "To display the OSPF routing table",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 77,
    category: "CCNA",
    subcategory: "OSPF Commands",
    question:
      "What is the purpose of the OSPF 'show ip ospf interface brief' command?",
    answer: "To display a brief summary of OSPF interfaces",
    options: [
      "To display a brief summary of OSPF interfaces",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
];

export default SAMPLE_FLASHCARDS;
