const SAMPLE_FLASHCARDS = [
  {
    id: 1,
    category: "React",
    question: "What is React?",
    answer: "A library for managing user interfaces",
    options: [
      "A library for managing user interfaces",
      "A JavaScript framework for backend development",
      "A CSS pre-processor",
      "A database query language",
    ],
  },
  {
    id: 2,
    category: "CCNA",
    question: "What does OSI stand for?",
    answer: "Open Systems Interconnection",
    options: [
      "Open Systems Interconnection",
      "Operating System Interface",
      "Optimal Signal Indicator",
      "Organized System Integration",
    ],
  },
  {
    id: 3,
    category: "CCNA",
    question: "Which layer of the OSI model deals with routing?",
    answer: "Network Layer",
    options: [
      "Data Link Layer",
      "Network Layer",
      "Transport Layer",
      "Application Layer",
    ],
  },
  {
    id: 4,
    category: "CCNA",
    question: "What is the default subnet mask for a Class C IP address?",
    answer: "255.255.255.0",
    options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"],
  },
  {
    id: 5,
    category: "CCNA",
    question: "Which protocol is used for sending email?",
    answer: "SMTP",
    options: ["HTTP", "FTP", "SMTP", "SNMP"],
  },
  {
    id: 6,
    category: "CCNA",
    question: "What is the purpose of a VLAN?",
    answer: "To segment a network",
    options: [
      "To create a virtual environment",
      "To encrypt data packets",
      "To segment a network",
      "To prioritize network traffic",
    ],
  },
  {
    id: 7,
    category: "React",
    question: "What is JSX?",
    answer: "JavaScript XML",
    options: [
      "JavaScript Extension",
      "JavaScript XML",
      "JavaScript X-Path",
      "JavaScript JSON",
    ],
  },
  {
    id: 8,
    category: "React",
    question: "Which hook is used for side-effects?",
    answer: "useEffect",
    options: ["useState", "useEffect", "useContext", "useReducer"],
  },
  {
    id: 9,
    category: "React",
    question: "What is Redux?",
    answer: "A state management library",
    options: [
      "A JavaScript framework",
      "A state management library",
      "A CSS framework",
      "A backend library",
    ],
  },
  {
    id: 10,
    category: "React",
    question: "What is React Router?",
    answer: "A routing library for React",
    options: [
      "A state management library",
      "A routing library for React",
      "A CSS framework",
      "A backend library",
    ],
  },
  {
    id: 11,
    category: "React",
    question: "What is a React component?",
    answer: "A reusable piece of UI",
    options: [
      "A function",
      "A reusable piece of UI",
      "An HTML element",
      "A JavaScript object",
    ],
  },
  {
    id: 12,
    category: "React",
    question: "What is React's virtual DOM?",
    answer: "An in-memory representation of the real DOM elements",
    options: [
      "A physical DOM",
      "An in-memory representation of the real DOM elements",
      "A set of APIs",
      "A database",
    ],
  },
  {
    id: 13,
    category: "React",
    question: "What is a React Fragment?",
    answer: "A way to return multiple elements",
    options: [
      "A way to return multiple elements",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 14,
    category: "React",
    question: "What is a React Portal?",
    answer:
      "A way to render children into a DOM node that exists outside the DOM hierarchy",
    options: [
      "A way to render children into a DOM node that exists outside the DOM hierarchy",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 15,
    category: "React",
    question: "What is Context in React?",
    answer:
      "A way to pass data through the component tree without having to pass props down manually",
    options: [
      "A way to pass data through the component tree without having to pass props down manually",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 16,
    category: "React",
    question: "What is a React Hook?",
    answer:
      "A function that lets you use state and other React features without writing a class",
    options: [
      "A function that lets you use state and other React features without writing a class",
      "A type of component",
      "A loop",
      "A conditional rendering method",
    ],
  },
  {
    id: 17,
    category: "CCNA",
    question: "What is the range of private IP addresses for Class A?",
    answer: "10.0.0.0 to 10.255.255.255",
    options: [
      "10.0.0.0 to 10.255.255.255",
      "172.16.0.0 to 172.31.255.255",
      "192.168.0.0 to 192.168.255.255",
      "None of the above",
    ],
  },
  {
    id: 18,
    category: "CCNA",
    question: "What is NAT?",
    answer: "Network Address Translation",
    options: [
      "Network Address Translation",
      "Network Allocation Table",
      "Network Access Token",
      "None of the above",
    ],
  },
  {
    id: 19,
    category: "CCNA",
    question: "What does DHCP stand for?",
    answer: "Dynamic Host Configuration Protocol",
    options: [
      "Dynamic Host Configuration Protocol",
      "Data High Connectivity Protocol",
      "Dynamic Hyper Control Protocol",
      "Direct Host Control Protocol",
    ],
  },
  {
    id: 20,
    category: "CCNA",
    question: "What is the function of ICMP?",
    answer: "Error reporting and diagnostics",
    options: [
      "Error reporting and diagnostics",
      "Internet Control Message Protocol",
      "Internal Configuration Management Protocol",
      "None of the above",
    ],
  },
  {
    id: 21,
    category: "CCNA",
    question: "What is the range of Class B private IP addresses?",
    answer: "172.16.0.0 to 172.31.255.255",
    options: [
      "10.0.0.0 to 10.255.255.255",
      "172.16.0.0 to 172.31.255.255",
      "192.168.0.0 to 192.168.255.255",
      "None of the above",
    ],
  },
  {
    id: 22,
    category: "CCNA",
    question: "What is the purpose of the Spanning Tree Protocol (STP)?",
    answer: "To prevent network loops",
    options: [
      "To prevent network loops",
      "To create network loops",
      "To manage VLANs",
      "To encrypt data packets",
    ],
  },
  {
    id: 23,
    category: "CCNA",
    question: "Which protocol is used for remote terminal connection?",
    answer: "Telnet",
    options: ["HTTP", "Telnet", "FTP", "SSH"],
  },
  {
    id: 24,
    category: "CCNA",
    question: "What does VPN stand for?",
    answer: "Virtual Private Network",
    options: [
      "Virtual Public Network",
      "Virtual Private Network",
      "Variable Port Network",
      "None of the above",
    ],
  },
  {
    id: 25,
    category: "CCNA",
    question: "What is the purpose of DNS?",
    answer: "To translate domain names to IP addresses",
    options: [
      "To translate domain names to IP addresses",
      "To provide routing services",
      "To manage network devices",
      "To encrypt data packets",
    ],
  },
  {
    id: 26,
    category: "CCNA",
    question: "What is the standard port for HTTP?",
    answer: "80",
    options: ["21", "22", "80", "443"],
  },
  {
    id: 27,
    category: "CCNA",
    question: "What is the function of a firewall?",
    answer: "To filter incoming and outgoing network traffic",
    options: [
      "To filter incoming and outgoing network traffic",
      "To provide DNS services",
      "To manage IP addresses",
      "None of the above",
    ],
  },
  {
    id: 28,
    category: "CCNA",
    question: "What does OSPF stand for?",
    answer: "Open Shortest Path First",
    options: [
      "Open Shortest Path First",
      "Optimal Signal Path Finding",
      "Open Signal Path First",
      "Optimal Shortest Path Finding",
    ],
  },
  {
    id: 29,
    category: "CCNA",
    question: "What is the OSPF default administrative distance?",
    answer: "110",
    options: ["100", "110", "120", "130"],
  },
  {
    id: 30,
    category: "CCNA",
    question: "What is the purpose of OSPF areas?",
    answer: "To segment an OSPF network into smaller parts",
    options: [
      "To segment an OSPF network into smaller parts",
      "To prioritize OSPF routes",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  // ... Continue with more OSPF questions

  {
    id: 47,
    category: "CCNA",
    question: "What is the main difference between TCP and UDP?",
    answer: "TCP is connection-oriented, UDP is connectionless",
    options: [
      "TCP is faster than UDP",
      "TCP is connection-oriented, UDP is connectionless",
      "TCP uses IP, UDP uses ICMP",
      "None of the above",
    ],
  },
  {
    id: 48,
    category: "CCNA",
    question: "What port does UDP use for DNS queries?",
    answer: "53",
    options: ["53", "80", "443", "8080"],
  },
  {
    id: 49,
    category: "CCNA",
    question: "Which STP state immediately follows the blocking state?",
    answer: "Listening",
    options: ["Listening", "Learning", "Forwarding", "Disabled"],
  },
  {
    id: 50,
    category: "CCNA",
    question: "What wireless standard operates at 5GHz frequency?",
    answer: "802.11a",
    options: ["802.11a", "802.11b", "802.11g", "802.11n"],
  },
  {
    id: 51,
    category: "CCNA",
    question: "What is the purpose of WPA in a wireless network?",
    answer: "To provide security through encryption",
    options: [
      "To provide security through encryption",
      "To boost signal strength",
      "To provide routing services",
      "None of the above",
    ],
  },
  {
    id: 52,
    category: "CCNA",
    question: "What is the default STP priority?",
    answer: "32768",
    options: ["1024", "4096", "32768", "65536"],
  },
  {
    id: 53,
    category: "CCNA",
    question: "What is the maximum hop count for OSPF?",
    answer: "Infinite",
    options: ["15", "16", "Infinite", "None of the above"],
  },
  {
    id: 54,
    category: "CCNA",
    question: "What is the purpose of the 'show ip ospf neighbor' command?",
    answer: "To display OSPF neighbor information",
    options: [
      "To display OSPF routes",
      "To display OSPF neighbor information",
      "To display OSPF settings",
      "None of the above",
    ],
  },
  {
    id: 55,
    category: "CCNA",
    question: "What is the OSPF Router ID format?",
    answer: "32-bit number",
    options: [
      "16-bit number",
      "32-bit number",
      "48-bit number",
      "64-bit number",
    ],
  },
  {
    id: 56,
    category: "CCNA",
    question: "What is the default hello interval for OSPF?",
    answer: "10 seconds",
    options: ["5 seconds", "10 seconds", "30 seconds", "60 seconds"],
  },
  {
    id: 57,
    category: "CCNA",
    question: "What is the purpose of the OSPF DR (Designated Router)?",
    answer: "To optimize OSPF network traffic",
    options: [
      "To optimize OSPF network traffic",
      "To act as a backup router",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 58,
    category: "CCNA",
    question: "What is the purpose of the 'cost' in OSPF?",
    answer: "To determine the best path for data packets",
    options: [
      "To determine the best path for data packets",
      "To set the priority of a router",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 59,
    category: "CCNA",
    question: "What is the purpose of the OSPF LSA (Link-State Advertisement)?",
    answer: "To advertise routing information",
    options: [
      "To advertise routing information",
      "To encrypt OSPF packets",
      "To set the priority of a router",
      "None of the above",
    ],
  },
  {
    id: 60,
    category: "CCNA",
    question:
      "What is the default OSPF hello interval on a point-to-point network?",
    answer: "10 seconds",
    options: ["5 seconds", "10 seconds", "30 seconds", "60 seconds"],
  },
  {
    id: 61,
    category: "CCNA",
    question: "What is the OSPF network command used for?",
    answer: "To specify which interfaces will participate in OSPF",
    options: [
      "To specify which interfaces will participate in OSPF",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 62,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'area range' command?",
    answer: "To summarize routes at an area boundary",
    options: [
      "To summarize routes at an area boundary",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 63,
    category: "CCNA",
    question: "What is the purpose of the 'show ip ospf interface' command?",
    answer: "To display OSPF-related interface information",
    options: [
      "To display OSPF routes",
      "To display OSPF-related interface information",
      "To display OSPF settings",
      "None of the above",
    ],
  },
  {
    id: 64,
    category: "CCNA",
    question: "What is the OSPF RID (Router ID) used for?",
    answer: "To uniquely identify a router in an OSPF network",
    options: [
      "To uniquely identify a router in an OSPF network",
      "To set OSPF priority",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 65,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'network' command?",
    answer: "To enable OSPF on specified interfaces",
    options: [
      "To enable OSPF on specified interfaces",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 66,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'passive-interface' command?",
    answer: "To prevent OSPF updates from being sent out an interface",
    options: [
      "To prevent OSPF updates from being sent out an interface",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 67,
    category: "CCNA",
    question:
      "What is the purpose of the OSPF 'default-information originate' command?",
    answer: "To generate a default route into OSPF",
    options: [
      "To generate a default route into OSPF",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 68,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'area' command?",
    answer: "To assign an interface to a specific OSPF area",
    options: [
      "To assign an interface to a specific OSPF area",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 69,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'router-id' command?",
    answer: "To manually set the OSPF router ID",
    options: [
      "To manually set the OSPF router ID",
      "To set OSPF priority",
      "To encrypt OSPF packets",
      "None of the above",
    ],
  },
  {
    id: 70,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'redistribute' command?",
    answer: "To inject routes from another routing protocol into OSPF",
    options: [
      "To inject routes from another routing protocol into OSPF",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 71,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'summary-address' command?",
    answer: "To manually configure OSPF route summarization",
    options: [
      "To manually configure OSPF route summarization",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 72,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'timers' command?",
    answer: "To manually set OSPF hello and dead intervals",
    options: [
      "To manually set OSPF hello and dead intervals",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 73,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'virtual-link' command?",
    answer: "To configure an OSPF virtual link",
    options: [
      "To configure an OSPF virtual link",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 74,
    category: "CCNA",
    question:
      "What is the purpose of the OSPF 'clear ip ospf process' command?",
    answer: "To reset the OSPF process",
    options: [
      "To reset the OSPF process",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 75,
    category: "CCNA",
    question:
      "What is the purpose of the OSPF 'show ip ospf database' command?",
    answer: "To display the OSPF link-state database",
    options: [
      "To display the OSPF link-state database",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 76,
    category: "CCNA",
    question: "What is the purpose of the OSPF 'show ip ospf route' command?",
    answer: "To display the OSPF routing table",
    options: [
      "To display the OSPF routing table",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
  {
    id: 77,
    category: "CCNA",
    question:
      "What is the purpose of the OSPF 'show ip ospf interface brief' command?",
    answer: "To display a brief summary of OSPF interfaces",
    options: [
      "To display a brief summary of OSPF interfaces",
      "To set OSPF router ID",
      "To set OSPF priority",
      "None of the above",
    ],
  },
];

export default SAMPLE_FLASHCARDS;
